server:
  port: 8080
front:
#  url: http://ssabab.com
  url: http://localhost:3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/ssabab?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - openid

logging:
  level:
    org.springframework.security: INFO
# jwt 추가
jwt:
  secret: ${JWT_SECRET_KEY} # 실제 시크릿 키는 환경 변수로 대체
  access-token-expiry: 1800     # Access Token 유효기간 (초) - 1800초 == 30분
  refresh-token-expiry: 604800 # Refresh Token 유효기간 (초) - 604800초 == 7일
